### ISSUE TITLE
Undeclared `stepsUntrodden` variable

### ISSUE THREAD

**Issue by sergiu-paraschiv** [angus-c/literary.js#9]
https://github.com/angus-c/literary.js/blob/master/book/borges/prime.js#L5
You should really use `var` to declare `stepsUntrodden`: http://stackoverflow.com/questions/15985875/effect-of-declared-and-undeclared-variables.

If you don't then it becomes a global:

    monstersAscendingAStaircase(20);
    console.log(stepsUntrodden);

**Comment by angus-c** [comment]
Sure, but this is intentionally stylized code as would have been written by these authors. So anything goes. As I said in the book intro - you wouldn't want to use some of this syntax in production

**Comment by sergiu-paraschiv** [comment]
I enjoy the art in purity and exactness more than anything else. But yes, this being artistic expression there's artistic license :)
